New Website v1.0
zkSNACKs/zkSNACKsSite pull request #1
Opened 2020-05-11 10:01 UTC by molnard

zkSNACKs website remade with similar technology considerations as the wasabiwallet website.

2020-05-12 11:18 UTC, jmacato reviewed
It looks really great! Only have a couple of comments:

1: Sometimes the animated video background in the first part of the website can interfere with the zkSNACKs logo on certain screen sizes (mine is 1600x900), perhaps we could add either shadows or overlay to improve contrast? 
![image](https://user-images.githubusercontent.com/16554748/81679873-20331000-9485-11ea-9484-3d09c108736d.png)

2. Would be great if we can find a vectorized version of the logos instead of bitmaps in the `As Seen On` part. 
![image](https://user-images.githubusercontent.com/16554748/81680102-53759f00-9485-11ea-99fd-e593eaeb02cf.png)

2020-05-12 16:02 UTC, ghost requested changes
This is very difficult to read.

![screenshot_20200512_175856](https://user-images.githubusercontent.com/30683012/81717010-56b75d80-947a-11ea-8d2f-9434162f5e77.png)

Change `Which we are proud of` to `We are proud of`.

Adam is no longer the CTO, David should be there too.

Maybe add that zksnacks is an open source company.

2020-05-12 17:27 UTC, yahiheb commented
> Change Which we are proud of to We are proud of.

ACK.

2020-05-12 17:29 UTC, yahiheb commented
Clicking on `Mission` or `WHICH WE ARE PROUD OF`, the header hides the title:

![Capture](https://user-images.githubusercontent.com/52379387/81725807-af8cf300-9486-11ea-97cf-8436ae25305a.PNG)

It should be like this:

![Capture1](https://user-images.githubusercontent.com/52379387/81725903-d4816600-9486-11ea-85e8-e1b24eb82217.PNG)

2020-05-26 15:19 UTC, RiccardoMasutti requested changes

2020-05-26 15:19 UTC, RiccardoMasutti commented on wwwroot/index.html
> +						Nowadays it is all about individuals’ digital privacy, governments and organisations are
```suggestion
						Nowadays it is all about individuals’ <strong>digital privacy</strong>, governments and organisations are
```

2020-05-26 15:19 UTC, RiccardoMasutti commented on wwwroot/index.html
> +						making steps to protect privacy in the digital world. We believe that privacy is both
```suggestion
						making steps to <strong>protect privacy in the digital world</strong>. We believe that privacy is both
```

2020-05-26 15:19 UTC, RiccardoMasutti commented on wwwroot/index.html
> +						This is why we focus on your digital financial privacy.
```suggestion
						This is why <strong>we focus on your digital financial privacy</strong>.
```

2020-05-26 15:19 UTC, RiccardoMasutti commented on wwwroot/index.html
> +									zkSNACKs was established to research the possibilities for Bitcoin fungibility
```suggestion
									zkSNACKs was established to research the possibilities for <strong>Bitcoin fungibility</strong>
```

2020-05-26 15:19 UTC, RiccardoMasutti commented on wwwroot/index.html
> +									Our mission is to equip you with powerful tools to secure your privacy.
```suggestion
									Our mission is to equip you with powerful tools to <strong>secure your privacy</strong>.
```

2020-05-26 15:19 UTC, RiccardoMasutti commented on wwwroot/index.html
> +									zkSNACKs’ flagship product is a privacy oriented Bitcoin wallet, called the Wasabi
```suggestion
									zkSNACKs’ flagship product is a <strong>privacy oriented Bitcoin wallet</strong>, called the <a class="go-to" href="https://wasabiwallet.io">Wasabi
```

2020-05-26 15:19 UTC, RiccardoMasutti commented on wwwroot/index.html
> +									<a class="go-to" href="http://wasabiwallet.io">Go to website.</a>
```suggestion
```

2020-05-26 15:19 UTC, RiccardoMasutti commented on wwwroot/index.html
> +									Wallet. <br>
```suggestion
									Wallet</a>. <br>
```

2020-05-26 15:19 UTC, RiccardoMasutti commented on wwwroot/index.html
> +								Wasabi Wallet listed on <a class="bitcoin-anonymous" href="http://bitcoin.org">
```suggestion
								Wasabi Wallet listed on <a class="bitcoin-anonymous" href="https://bitcoin.org/" target="_blank">
```

2020-05-26 15:19 UTC, RiccardoMasutti commented on wwwroot/index.html
> +							<a class="slide" href="https://www.coindesk.com/privacy-bitcoin-wallets/" target="_blank">
```suggestion
							<a class="slide" href="https://www.coindesk.com/privacy-bitcoin-wallets/" target="_blank" rel="external nofollow">
```

2020-05-26 15:19 UTC, RiccardoMasutti commented on wwwroot/index.html
> +								<img src="assets/client-logos/CoinDesk_logo.png" alt="CoinDesk">
```suggestion
								<img src="assets/client-logos/CoinDesk_logo.png" alt="CoinDesk" loading="lazy">
```

2020-05-26 15:19 UTC, RiccardoMasutti commented on wwwroot/index.html
> +								target="_blank"> <img src="assets/client-logos/coinpick.png" alt="coinpick"> </a>
```suggestion
								target="_blank" rel="external nofollow"> <img src="assets/client-logos/coinpick.png" alt="coinpick" loading="lazy"> </a>
```

2020-05-26 15:19 UTC, RiccardoMasutti commented on wwwroot/index.html
> +							<a class="slide" href="https://cryptochan.org/stream/id/1532515705/" target="_blank"> <img
```suggestion
							<a class="slide" href="https://cryptochan.org/stream/id/1532515705/" target="_blank" rel="external nofollow"> <img
```

2020-05-26 15:19 UTC, RiccardoMasutti commented on wwwroot/index.html
> +									src="assets/client-logos/cryptochan.png" alt="cryptochan">
```suggestion
									src="assets/client-logos/cryptochan.png" alt="cryptochan" loading="lazy">
```

2020-05-26 15:19 UTC, RiccardoMasutti commented on wwwroot/index.html
> +								target="_blank"> <img src="assets/client-logos/cryptoinfobase.png" alt="cryptoinfobase">
```suggestion
								target="_blank" rel="external nofollow"> <img src="assets/client-logos/cryptoinfobase.png" alt="cryptoinfobase" loading="lazy">
```

2020-05-26 15:19 UTC, RiccardoMasutti commented on wwwroot/index.html
> +							<a class="slide" href="https://www.cryptotraders.eu/what-is-wasabi-wallet/" target="_blank">
```suggestion
							<a class="slide" href="https://www.cryptotraders.eu/what-is-wasabi-wallet/" target="_blank" rel="external nofollow">
```

2020-05-26 15:19 UTC, RiccardoMasutti commented on wwwroot/index.html
> +								<img src="assets/client-logos/cryptotraders.png" alt="cryptotraders"> </a>
```suggestion
								<img src="assets/client-logos/cryptotraders.png" alt="cryptotraders" loading="lazy"> </a>
```

2020-05-26 15:38 UTC, RiccardoMasutti requested changes

2020-05-26 15:38 UTC, RiccardoMasutti commented on wwwroot/index.html
> +								target="_blank"> <img src="assets/client-logos/Yahoo_Finance_Logo.png"
```suggestion
								target="_blank" rel="external nofollow"> <img src="assets/client-logos/Yahoo_Finance_Logo.png"
```

2020-05-26 15:38 UTC, RiccardoMasutti commented on wwwroot/index.html
> +									alt="Yahoo_Finance"> </a>
```suggestion
									alt="Yahoo_Finance" loading="lazy"> </a>
```

2020-05-26 15:38 UTC, RiccardoMasutti commented on wwwroot/index.html
> +								target="_blank"> <img src="assets/client-logos/reddit.png" alt="reddit"></a>
```suggestion
								target="_blank" rel="external nofollow"> <img src="assets/client-logos/reddit.png" alt="reddit" loading="lazy"></a>
```

2020-05-26 15:38 UTC, RiccardoMasutti commented on wwwroot/index.html
> +								target="_blank"> <img src="assets/client-logos/CCN-Logo.png" alt="CCN-Logo"> </a>
```suggestion
								target="_blank" rel="external nofollow"> <img src="assets/client-logos/CCN-Logo.png" alt="CCN-Logo" loading="lazy"> </a>
```

2020-05-26 15:38 UTC, RiccardoMasutti commented on wwwroot/index.html
> +								target="_blank"> <img src="assets/client-logos/medium-logo.jpg" alt="medium-logo">
```suggestion
								target="_blank" rel="external nofollow"> <img src="assets/client-logos/medium-logo.jpg" alt="medium-logo" loading="lazy">
```

2020-05-26 15:38 UTC, RiccardoMasutti commented on wwwroot/index.html
> +								target="_blank"> <img src="assets/client-logos/crypto-new-media.jpg"
```suggestion
								target="_blank" rel="external nofollow"> <img src="assets/client-logos/crypto-new-media.jpg"
```

2020-05-26 15:38 UTC, RiccardoMasutti commented on wwwroot/index.html
> +									alt="crypto-new-media"> </a>
```suggestion
									alt="crypto-new-media" loading="lazy"> </a>
```

2020-05-26 15:38 UTC, RiccardoMasutti commented on wwwroot/index.html
> +								target="_blank"> <img src="assets/client-logos/Bitcoin-Exchange-Guide.png"
```suggestion
								target="_blank" rel="external nofollow"> <img src="assets/client-logos/Bitcoin-Exchange-Guide.png"
```

2020-05-26 15:38 UTC, RiccardoMasutti commented on wwwroot/index.html
> +									alt="Bitcoin-Exchange-Guide">
```suggestion
									alt="Bitcoin-Exchange-Guide" loading="lazy">
```

2020-05-26 15:38 UTC, RiccardoMasutti commented on wwwroot/index.html
> +								target="_blank"> <img src="assets/client-logos/steemit.png" alt="steemit"> </a>
```suggestion
								target="_blank" rel="external nofollow"> <img src="assets/client-logos/steemit.png" alt="steemit" loading="lazy"> </a>
```

2020-05-26 15:38 UTC, RiccardoMasutti commented on wwwroot/index.html
> +								target="_blank"> <img src="assets/client-logos/cryptowiki.png" alt="cryptowiki">
```suggestion
								target="_blank" rel="external nofollow"> <img src="assets/client-logos/cryptowiki.png" alt="cryptowiki" loading="lazy">
```

2020-05-26 15:38 UTC, RiccardoMasutti commented on wwwroot/index.html
> +								target="_blank"> <img src="assets/client-logos/nulltx.png" alt="nulltx"> </a>
```suggestion
								target="_blank" rel="external nofollow"> <img src="assets/client-logos/nulltx.png" alt="nulltx" loading="lazy"> </a>
```

2020-05-26 15:38 UTC, RiccardoMasutti commented on wwwroot/index.html
> +							<a class="slide" href="https://nulltx.com/what-is-wasabi-wallet/" target="_blank"> <img
```suggestion
							<a class="slide" href="https://nulltx.com/what-is-wasabi-wallet/" target="_blank" rel="external nofollow"> <img
```

2020-05-26 15:38 UTC, RiccardoMasutti commented on wwwroot/index.html
> +									src="assets/client-logos/Coin-News-Telegraph-logo.png" alt="Coin-News-Telegraph">
```suggestion
									src="assets/client-logos/Coin-News-Telegraph-logo.png" alt="Coin-News-Telegraph" loading="lazy">
```

2020-05-26 15:38 UTC, RiccardoMasutti commented on wwwroot/index.html
> +								target="_blank"> <img src="assets/client-logos/Bitcoin-Insight-Logo.png"
```suggestion
								target="_blank" rel="external nofollow"> <img src="assets/client-logos/Bitcoin-Insight-Logo.png"
```

2020-05-26 15:38 UTC, RiccardoMasutti commented on wwwroot/index.html
> +									alt="Bitcoin-Insight">
```suggestion
									alt="Bitcoin-Insight" loading="lazy">
```

2020-05-26 15:38 UTC, RiccardoMasutti commented on wwwroot/index.html
> +								target="_blank"> <img src="assets/client-logos/btc_manager.png" alt="btc_manager">
```suggestion
								target="_blank" rel="external nofollow"> <img src="assets/client-logos/btc_manager.png" alt="btc_manager" loading="lazy">
```

2020-05-26 15:38 UTC, RiccardoMasutti commented on wwwroot/index.html
> +								target="_blank"> <img src="assets/client-logos/Insidebitcoins.png" alt="Insidebitcoins">
```suggestion
								target="_blank" rel="external nofollow"> <img src="assets/client-logos/Insidebitcoins.png" alt="Insidebitcoins" loading="lazy">
```

2020-05-26 15:38 UTC, RiccardoMasutti commented on wwwroot/index.html
> +								target="_blank"> <img src="assets/client-logos/coinstaker.jpg" alt="coinstaker">
```suggestion
								target="_blank" rel="external nofollow"> <img src="assets/client-logos/coinstaker.jpg" alt="coinstaker" loading="lazy">
```

2020-05-26 15:38 UTC, RiccardoMasutti commented on wwwroot/index.html
> +								target="_blank"> <img src="assets/client-logos/Coinrussia.png" alt="Coinrussia">
```suggestion
								target="_blank" rel="external nofollow"> <img src="assets/client-logos/Coinrussia.png" alt="Coinrussia" loading="lazy">
```

2020-05-26 15:38 UTC, RiccardoMasutti commented on wwwroot/index.html
> +								target="_blank"> <img src="assets/client-logos/blockpublisher_logo.png"
```suggestion
								target="_blank" rel="external nofollow"> <img src="assets/client-logos/blockpublisher_logo.png"
```

2020-05-26 15:38 UTC, RiccardoMasutti commented on wwwroot/index.html
> +									alt="blockpublisher">
```suggestion
									alt="blockpublisher" loading="lazy">
```

2020-05-26 15:38 UTC, RiccardoMasutti commented on wwwroot/index.html
> +								target="_blank"> <img src="assets/client-logos/digitalbitcoinlogo.png"
```suggestion
								target="_blank" rel="external nofollow"> <img src="assets/client-logos/digitalbitcoinlogo.png"
```

2020-05-26 15:38 UTC, RiccardoMasutti commented on wwwroot/index.html
> +									alt="digitalbitcoin">
```suggestion
									alt="digitalbitcoin" loading="lazy">
```

2020-05-26 15:38 UTC, RiccardoMasutti commented on wwwroot/index.html
> +								target="_blank"> <img src="assets/client-logos/Bitcoin_Kurier.png" alt="Bitcoin_Kurier">
```suggestion
								target="_blank" rel="external nofollow"> <img src="assets/client-logos/Bitcoin_Kurier.png" alt="Bitcoin_Kurier" loading="lazy">
```

2020-05-26 15:38 UTC, RiccardoMasutti commented on wwwroot/index.html
> +								<img class="contact-picture" src="assets/contact/thumb-1.jpg">
```suggestion
								<img class="contact-picture" src="assets/contact/thumb-1.jpg" loading="lazy">
```

2020-05-26 15:38 UTC, RiccardoMasutti commented on wwwroot/index.html
> +											alt="email">
```suggestion
											alt="email" loading="lazy">
```

2020-05-26 15:38 UTC, RiccardoMasutti commented on wwwroot/index.html
> +									<a href="https://www.linkedin.com/in/gergelyhajdu" target="_blank"><img class="ml-1"
```suggestion
									<a href="https://www.linkedin.com/in/gergelyhajdu" target="_blank" rel="external nofollow"><img class="ml-1"
```

2020-05-26 15:38 UTC, RiccardoMasutti commented on wwwroot/index.html
> +											src="assets/linkedin-in-brands.svg" alt="linkedin"> </a>
```suggestion
											src="assets/linkedin-in-brands.svg" alt="linkedin" loading="lazy"> </a>
```

2020-05-26 15:38 UTC, RiccardoMasutti commented on wwwroot/index.html
> +								<img class="contact-picture" src="assets/contact/thumb-2.jpg">
```suggestion
								<img class="contact-picture" src="assets/contact/thumb-2.jpg" loading="lazy">
```

2020-05-26 15:38 UTC, RiccardoMasutti commented on wwwroot/index.html
> +											alt="email">
```suggestion
											alt="email" loading="lazy">
```

2020-05-26 15:38 UTC, RiccardoMasutti commented on wwwroot/index.html
> +									<a href="https://www.linkedin.com/in/balint-harmat-0a673634/" target="_blank"> <img
```suggestion
									<a href="https://www.linkedin.com/in/balint-harmat-0a673634/" target="_blank" rel="external nofollow"> <img
```

2020-05-26 15:38 UTC, RiccardoMasutti commented on wwwroot/index.html
> +											class="ml-1" src="assets/linkedin-in-brands.svg" alt="linkedin"> </a>
```suggestion
											class="ml-1" src="assets/linkedin-in-brands.svg" alt="linkedin" loading="lazy"> </a>
```

2020-05-26 16:03 UTC, RiccardoMasutti requested changes

2020-05-26 16:03 UTC, RiccardoMasutti commented on wwwroot/index.html
> +									<a class="bitcoin-anonymous" href="https://bitcoin.org/en/protect-your-privacy">Many
```suggestion
									<a class="bitcoin-anonymous" href="https://bitcoin.org/en/protect-your-privacy" target="_blank">Many
```

2020-05-26 16:03 UTC, RiccardoMasutti commented on wwwroot/index.html
> +								<img class="contact-picture" src="assets/contact/1112.jpg">
```suggestion
								<img class="contact-picture" src="assets/contact/1112.jpg" loading="lazy">
```

2020-05-26 16:03 UTC, RiccardoMasutti commented on wwwroot/index.html
> +									<a href="mailto:adam.ficsor@zksnacks.com"> <img src="assets/envelope-solid.svg">
```suggestion
									<a href="mailto:adam.ficsor@zksnacks.com"> <img src="assets/envelope-solid.svg" loading="lazy">
```

2020-05-26 16:03 UTC, RiccardoMasutti commented on wwwroot/index.html
> +											src="assets/github-brands.svg" alt="github"> </a>
```suggestion
											src="assets/github-brands.svg" alt="github" loading="lazy"> </a>
```

2020-05-26 16:03 UTC, RiccardoMasutti commented on wwwroot/index.html
> +											src="assets/twitter-brands.svg" alt="twitter"> </a>
```suggestion
											src="assets/twitter-brands.svg" alt="twitter" loading="lazy"> </a>
```

2020-05-26 16:03 UTC, RiccardoMasutti commented on wwwroot/index.html
> +											src="assets/medium-brands.svg" alt="medium"> </a>
```suggestion
											src="assets/medium-brands.svg" alt="medium" loading="lazy"> </a>
```

2020-05-26 16:03 UTC, RiccardoMasutti commented on wwwroot/index.html
> +								<img class="contact-picture" src="assets/contact/unnamed.png">
```suggestion
								<img class="contact-picture" src="assets/contact/unnamed.png" loading="lazy">
```

2020-05-26 16:03 UTC, RiccardoMasutti commented on wwwroot/index.html
> +											src="assets/github-brands.svg" alt="github"> </a>
```suggestion
											src="assets/github-brands.svg" alt="github" loading="lazy"> </a>
```

2020-05-30 10:10 UTC, RiccardoMasutti commented
@molnard can you apply those updates please? Just small SEO tweaks

2020-05-31 11:35 UTC, molnard commented
The source is handled by a Hungarian web dev, he will do the changes. @hgergoil what is the status of this?

2020-06-02 09:58 UTC, hgergoil commented
End of this week Balazs will finish it.

2020-06-08 09:30 UTC, molnard commented
Main menu is too transparent 

![image](https://user-images.githubusercontent.com/9844978/84014957-6fcd0480-a97b-11ea-8f54-0307753cd8d4.png)

2020-07-07 09:27 UTC, molnard commented
Merging, @Rmartin1104 pls create PR with @RiccardoMasutti's changes.

2020-07-07 09:27 UTC, merged